In [54]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [6]:
transformer = joblib.load("../Models/pipelines/pipeline1.joblib")

In [7]:
transformer.transform([['male', 46, 2000, 'own']])

/home/estudiantes/Documents/Soft_elect2/ex1/env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/home/estudiantes/Documents/Soft_elect2/ex1/env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[0.48214286, 0.09629141, 0.        , 1.        , 0.        ,
        1.        , 0.        ]])

In [8]:
df = pd.read_csv("../data/german_credit_data-3.csv")

In [16]:
train, test = train_test_split(df, test_size=0.3, random_state=42)

In [17]:
features = ['Sex','Age','Credit amount','Housing']
y_train = (train['Risk']=='bad').astype('int')
X_train = train[features]
X_train_transformed = transformer.transform(X_train)

In [36]:
cross_v = cross_validate(LogisticRegression(), X_train_transformed , y_train, cv=5, return_train_score=True,
              scoring=['accuracy'])

print("{} +- {}". format(cross_v["test_accuracy"].mean(),
                         cross_v["test_accuracy"].std()))

0.7014285714285714 +- 0.014568627181693668


In [23]:
cross_v

{'fit_time': array([0.00671315, 0.00485396, 0.00473142, 0.00489473, 0.00415182]),
 'score_time': array([0.00044966, 0.00030518, 0.00041032, 0.00032568, 0.0002532 ]),
 'test_accuracy': array([0.70714286, 0.69285714, 0.67857143, 0.72142857, 0.70714286]),
 'train_accuracy': array([0.70178571, 0.70535714, 0.70892857, 0.69821429, 0.70178571])}

In [25]:
clf = LogisticRegression()
clf.fit(X_train_transformed, y_train)

LogisticRegression()

In [26]:
clf.predict_proba(transformer.transform([['male', 46, 2000, 'own']]))

/home/estudiantes/Documents/Soft_elect2/ex1/env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/home/estudiantes/Documents/Soft_elect2/ex1/env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[0.83685017, 0.16314983]])

In [27]:
clf.predict(transformer.transform([['male', 46, 2000, 'own']]))

/home/estudiantes/Documents/Soft_elect2/ex1/env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/home/estudiantes/Documents/Soft_elect2/ex1/env/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0])

In [40]:
cross_v_1 = cross_validate(KNeighborsClassifier(n_neighbors=20), X_train_transformed , y_train, cv=5, return_train_score=True,
              scoring=['accuracy'])
print("{} +- {}". format(cross_v_1["test_accuracy"].mean(),
                         cross_v_1["test_accuracy"].std()))

0.6928571428571428 +- 0.011952286093343947


In [49]:
cross_v_2 = cross_validate(DecisionTreeClassifier(max_depth=3), X_train_transformed , y_train, cv=5, return_train_score=True,
              scoring=['accuracy'])
print("Train {} +- {}". format(cross_v_1["train_accuracy"].mean(),
                         cross_v_1["train_accuracy"].std()))
print("Validation {} +- {}". format(cross_v_1["test_accuracy"].mean(),
                         cross_v_1["test_accuracy"].std()))

Train 0.7121428571428571 +- 0.007354021529276434
Validation 0.6928571428571428 +- 0.011952286093343947


In [53]:
cross_v_3 = cross_validate(RandomForestClassifier(n_estimators=100,max_depth=4), X_train_transformed , y_train, cv=5, return_train_score=True,
              scoring=['accuracy'])
print("Train {} +- {}". format(cross_v_1["train_accuracy"].mean(),
                         cross_v_1["train_accuracy"].std()))
print("Validation {} +- {}". format(cross_v_1["test_accuracy"].mean(),
                         cross_v_1["test_accuracy"].std()))

Train 0.7121428571428571 +- 0.007354021529276434
Validation 0.6928571428571428 +- 0.011952286093343947


In [56]:
cross_v_4 = cross_validate(SVC(kernel='linear', C=5), X_train_transformed , y_train, cv=5, return_train_score=True,
              scoring=['accuracy'])
print("Train {} +- {}". format(cross_v_1["train_accuracy"].mean(),
                         cross_v_1["train_accuracy"].std()))
print("Validation {} +- {}". format(cross_v_1["test_accuracy"].mean(),
                         cross_v_1["test_accuracy"].std()))

Train 0.7121428571428571 +- 0.007354021529276434
Validation 0.6928571428571428 +- 0.011952286093343947
